### ISSUE TITLE
Bad Coding Style

### ISSUE THREAD

**Issue by Omar3esam** [AhmedSaIah/Advent-of-code-2021#1]
I think in your Day2 file, you used the string length for a comparison between the commands entered, so when I use any word with the same length it did add some numbers to the indication variables, can you update the file with a fair comparison.

**Comment by AhmedSaIah** [comment]
Problem solved

**Comment by AhmedSaIah** [comment]
Hey enta

**Comment by AhmedSaIah** [comment]
> I think in your Day2 file, you used the string length for a comparison between the commands entered, so when I use any word with the same length it did add some numbers to the indication variables, can you update the file with a fair comparison.

a7aaaaaaa

**Comment by AhmedSaIah** [comment]
Is this making it usable whatever the location we pass to it?
```
func startOfDay(t time.Time) time.Time {
	year, month, day := t.Date()

	return time.Date(year, month, day, 0, 0, 0, 0, t.Location())
}
```
